### ISSUE TITLE
Cloud Functions support VPC-SC

### ISSUE THREAD

**Issue by Shaddowfaxx** [terraform-google-modules/terraform-google-vpc-service-controls#105]
### TL;DR

Cloud Functions currently have GA support for VPC-SC, per https://cloud.google.com/vpc-service-controls/docs/supported-products#table_functions. Can we update the repository to include best practices for implementing the automatic folder inclusion with current best practices/limitations using CF to monitor the folder? 

### Terraform Configuration

```hcl
N/A
```

### Terraform Version

```sh
N/A
```

**Comment by ba31** [comment]
would be good to update this repo as Cloud function start supported by the VPC Service Control
