### ISSUE TITLE
Using the example for bridge_service_perimeter module fails

### ISSUE THREAD

**Issue by bharathkkb** [terraform-google-modules/terraform-google-vpc-service-controls#25]
Using the example in [readme](https://github.com/terraform-google-modules/terraform-google-vpc-service-controls/blob/master/modules/bridge_service_perimeter/README.md) for `bridge_service_perimeter` fails because 
`bridge_service_perimeter_1` does not wait for `regular_service_perimeter_1` and `regular_service_perimeter_2` to be created. 
Error:
`Error: Error creating ServicePerimeter: googleapi: Error 400: A project is in a Service Perimeter Bridge but no regular Service Perimeter. Each project in a Service Perimeter Bridge must be in a regular Service Perimeter.`
Solutions:
I was able to fix this by introducing a computed attribute as an output like [create_time](https://www.terraform.io/docs/providers/google/r/access_context_manager_service_perimeter.html#create_time) into the output.

**Comment by aaron-lane** [comment]
@bharathkkb please submit a pull request if you have a working solution!

**Comment by bharathkkb** [comment]
@aaron-lane sounds good
