### ISSUE TITLE
Error while trying to define an access level with require_screen_lock

### ISSUE THREAD

**Issue by edruela** [terraform-google-modules/terraform-google-vpc-service-controls#27]
Configuration:

`module "access_level_members" {
  source                            = "terraform-google-modules/vpc-service-controls/google//modules/access_level"
  version                           = "~> 1.0"
  policy                            = module.org_policy.policy_id
  name                              = "terraform_members"
  members                           = ["serviceAccount:project-factory-111@my-project.iam.gserviceaccount.com"]
  allowed_device_management_levels  = []
  allowed_encryption_statuses       = []
  require_screen_lock               = true
  os_type                           = ""
}`

Error message from terraform:

Error: Error updating AccessLevel "accessPolicies/472883192766/accessLevels/terraform_members": googleapi: Error 400: Invalid JSON payload received. Unknown name "requireScreenLock" at 'access_level.basic.conditions[0].device_policy': Cannot find field.

  on .terraform/modules/access_level_members/terraform-google-modules-terraform-google-vpc-service-controls-47c09dc/modules/access_level/main.tf line 21, in resource "google_access_context_manager_access_level" "access_level":
  21: resource "google_access_context_manager_access_level" "access_level" {

**Comment by bharathkkb** [comment]
@edruela apologies for the delay. This seemed to be a provider issue: https://github.com/hashicorp/terraform-provider-google/issues/6195 that has been fixed.
Feel free to reopen if it is still happening.
