### ISSUE TITLE
Submodule README source update

### ISSUE THREAD

**Issue by ankiclockwise** [terraform-google-modules/terraform-google-vpc-service-controls#48]
**(please add the / after 'google' in the source)**

Regular Service Perimeter 
source          = "terraform-google-modules/vpc-service-controls/google//modules/regular_service_perimeter"

Access Level
source          = "terraform-google-modules/vpc-service-controls/google//modules/access_level"

Bridge Service Perimeter
source         = "terraform-google-modules/vpc-service-controls/google//modules/bridge_service_perimeter"

**Comment by aweberlopes** [comment]
Have opened a new pull request to fix it.

**Comment by aweberlopes** [comment]
https://github.com/terraform-google-modules/terraform-google-vpc-service-controls/pull/59

**Comment by aweberlopes** [comment]
can be closed
