### ISSUE TITLE
outputs in submodules are limited and possibly incorrect

### ISSUE THREAD

**Issue by michaeldeman** [terraform-google-modules/terraform-google-vpc-service-controls#49]
I am using _terraform-google-vpc-service-controls/modules/regular_service_perimeter_
to create a regular perimeter for a project.
I wanted to add the perimeter name as an output from the module and am unable to do so.

Looking at the code it appears that the output.tf for regular_service_perimeter only includes _value = var.shared_resources_ which is actually a parameter that should only be supplied for a bridge perimeter anyway?
I am on 3.0.x and it looks similar for 2.1.x.

**Comment by morgante** [comment]
Sure, feel free to add an output. We will review a PR.
