### ISSUE TITLE
additional parameters ingress_policies and egress_policies in regular service perimeter  needed

### ISSUE THREAD

**Issue by ankiclockwise** [terraform-google-modules/terraform-google-vpc-service-controls#53]

**Comment by aweberlopes** [comment]
Hello guys. Is somebody already started working on it?
If not i would pick it up and extend the module

**Comment by morgante** [comment]
Nobody is currently working on this. We would be happy to review a PR.

**Comment by aweberlopes** [comment]
Currently was on Vacation. Ingress rule allready implemented will focus on egress rule now. Hopefull release end of September

**Comment by aweberlopes** [comment]
#55 Added Pull Request happy if somebody can have a look on it

**Comment by aweberlopes** [comment]
The input will be used list for ingress and egress. The same for dry run:
```ingress_policies = [
    {
      "from" = {
        "sources" = {
          resources = [
            "projects/688789777678",
            "projects/557367936583",
            ""
          ],
          access_levels = [
            "aweberlopes_ip"
          ]
        },
        "identity_type" = "ANY_IDENTITY"
        "identities"    =  e[]
      }
      "to" = {
        "resources" = [
          "*"
        ]
        "operations" = {
          "bigquery.googleapis.com" = {
            "methods" = [
              "BigQueryStorage.ReadRows",
              "TableService.ListTables"
            ],
            "permissions" = [
              "bigquery.jobs.get"
            ]
          }
          "storage.googleapis.com" = {
            "methods" = [
              "google.storage.objects.create"
            ]
          }
        }
      }
    },
  ]```

**Comment by Mahsamtm** [comment]
I have created a new PR for ingress/egress policy could you please review 
https://github.com/terraform-google-modules/terraform-google-vpc-service-controls/pull/57/files

**Comment by aweberlopes** [comment]
i allready written a pull request for this topic.

**Comment by CAR** [comment]
The pull request https://github.com/terraform-google-modules/terraform-google-vpc-service-controls/pull/55 by @aweberlopes was finally accepted, see commit https://github.com/terraform-google-modules/terraform-google-vpc-service-controls/commit/f837a23b58065c53327a2de3236e70e57e7386e9. Looks great!

Hence, this issue might be closed.
