### ISSUE TITLE
GCR vs GAR

### ISSUE THREAD

**Issue by tejeshnandyala** [terraform-google-modules/terraform-google-vpc-service-controls#64]
hi,

i see that this automatic folder example is using GCR with cloud function. Is there a possibility to change it to GAR? if so, how can this be changed?

Currently i have a situation where my org policy is allowed only for allowed_values": ["in:europe-west2-locations", "in:europe-west3-locations"] and not entire eu locations. For GCR to be used i am being asked to update the org policy which i dont want to update.

How do we change to usage of GAR?

Thanks,

**Comment by morgante** [comment]
The underlying module is event_function: https://github.com/terraform-google-modules/terraform-google-event-function/blob/master/main.tf#L61

This uses GCS, not GCR. You can tweak the example to use a different region if you prefer.
