### ISSUE TITLE
protected_project_ids variable is not defined in the module, how do i use it?

### ISSUE THREAD

**Issue by tsm2k** [terraform-google-modules/terraform-google-vpc-service-controls#67]
### TL;DR

 it's been used in the example alright, but when i apply the code, it throws me this error "An argument named "protected_project_ids" is not expected here."
How do i resolve this?

### Terraform Configuration

```hcl
https://github.com/terraform-google-modules/terraform-google-vpc-service-controls/blob/master/examples/simple_example/main.tf

same as here
```

### Terraform Version

```sh
Terraform v1.0.11
on linux_amd64
+ provider registry.terraform.io/hashicorp/google v3.90.1
```

**Comment by morgante** [comment]
This is just an *example*. Examples are meant to show you how you can use the module.

You should copy and paste the example to your own configuration to get started.
